js_config:
# M加购 M抽奖 分享有礼
- Container:
  - - 1
  Env: jd_task_wuxian_custom
  KeyWord:
  - - M_WX_LUCK_DRAW_URL
  - - M_WX_ADD_CART_URL
  - - M_WX_CENTER_DRAW_URL
  - - ACTIVITY_ID
  - - SHARE_ACTIVITY_ID
  - - jd_task_wuxian_custom
  Name: kedaya_无线
  Script: jd_task_wuxian.js
  TimeOut: 0
  Wait: 5

# 组队 
- Container:
  - - 1
  Env: jd_cjwxTeam_custom
  KeyWord:
  - - jd_cjhy_activityUrl
  - - jd_cjhy_activityId
  - - jd_cjwxTeam_custom
  Name: kedaya_组队
  Script: jd_cjwxTeam.js  
  TimeOut: 0
  Wait: 5

## 微定制
- Container:
  - - 1
  Env: jd_w630_custom
  KeyWord:
  - - jd_wdz_activityId
  - - jd_wdz_activityUrl
  - - jd_w630_custom
  Name: kedaya_微定制
  Script: jd_w630.js
  TimeOut: 0
  Wait: 5

## 关注店铺
- Container:
  - - 1
  Env: jd_task_shopGift_custom
  KeyWord:
  - - M_WX_FOLLOW_DRAW_URL
  - - M_FOLLOW_SHOP_ARGV
  - - jd_task_shopGift_custom
  Name: kedaya_关注店铺
  Script: jd_task_shopGift.js
  TimeOut: 0
  Wait: 5

#京东店铺连续签到
- Container:
  - - 1
  Env: jd_task_shopSign_expand
  KeyWord:
  - - jd_task_shopSign_expand
  - - MyShoopToken
  - - SHOP_TOKENS
  - - DPQDTK
  Name: kedaya_店铺签到
  Script: jd_task_shopSign.js
  TimeOut: 0
  Wait: 5

# 打豆豆
- Container:
  - - 1
  Env: WXGAME_ACT_ID
  KeyWord:
  - - WXGAME_ACT_ID
  Name: 打豆豆
  Script: jd_doudou.js
  TimeOut: 0
  Wait: 5

# 通用大牌
- Container:
  - - 1
  Env: dpactId
  KeyWord:
  - - dpactId
  - - actId
  Name: 通用大牌
  Script: N_opencardL_COMMON.js
  TimeOut: 0
  Wait: 5

# 电脑配件
- Container:
  - - 1
  Env: computer_activityIdList
  KeyWord:
  - - computer_activityId
  - - computer_activityIdList
  Name: 电脑配件
  Script: jd_computer.js
  TimeOut: 0
  Wait: 5
  
# 入会有礼
- Container:
  - - 1
  Env: VENDER_ID
  KeyWord:
  - - VENDER_ID
  Name: 入会有礼
  Script: jd_OpenCard_Force.js
  TimeOut: 0
  Wait: 5

## 分享有礼
- Container:
  - - 1
  Env: SHARE_ACTIVITY_ID
  KeyWord:
  - - SHARE_ACTIVITY_ID
  Name: 分享有礼
  Script: jd_share.js
  TimeOut: 0
  Wait: 5

# 盲盒
- Container:
  - - 1
  Env: jd_mhurlList
  KeyWord:
  - - jd_mhurlList
  Name: 盲盒抽京豆
  Script: jd_mhtask.js
  TimeOut: 0
  Wait: 5

# 收藏有礼
- Container:
  - - 1
  Env: M_FAV_SHOP_ARGV
  KeyWord:
  - - M_FAV_SHOP_ARGV
  Name: M收藏有礼
  Script: m_jd_fav_shop_gift.js
  TimeOut: 0
  Wait: 5

# M幸运抽奖
- Container:
  - - 1
  Env: M_WX_LUCK_DRAW_URL
  KeyWord:
  - - M_WX_LUCK_DRAW_URL
  Name: M幸运抽奖
  Script: m_jd_wx_luckDraw.js
  TimeOut: 0
  Wait: 5

- Container:
  - - 1
  Env: jd_redrain_half_url
  KeyWord:
  - - jd_redrain_half_url
  Name: 半点京豆雨
  Script: jd_redrain_half.js
  TimeOut: 0
  Wait: 5

# 众筹许愿池
- Container:
  - - 1
  Env: wish_appIdArrList
  KeyWord:
  - - wish_appIdArrList
  - - wish_appNameArrList
  Name: 众筹许愿池
  Script: jd_wish.js
  TimeOut: 0
  Wait: 5

- Container:
  - - 1
  Env: comm_activityIDList|comm_endTimeList
  KeyWord:
  - - comm_activityIDList|comm_endTimeList
  Name: Joy_Jd_Open
  Script: jd_joyjd_open.js
  TimeOut: 0
  Wait: 5

- Container:
  - 1
  Env: PKC_TXGZYL
  KeyWord:
  - - PKC_TXGZYL
  Name: PKC特效关注有礼
  Script: pkc_txgzyl.js
  TimeOut: 0
  Wait: 3


- Container:
  - 1
  Env: PKC_GZYL
  KeyWord:
  - - PKC_GZYL
  Name: PKC关注有礼
  Script: pkc_gzyl.js
  TimeOut: 0
  Wait: 3